bundler_args: "--without development"
language: ruby
rvm:
- 2.1.2
- 2.1.3
- ruby-head
gemfile:
- Gemfile
matrix:
  allow_failures:
  - rvm: ruby-head
  fast_finish: true
services: memcache
before_install: gem install bundler
before_script:
- echo $PWD
- memcached -p 11212 -d
script:
- bundle exec rspec
notifications:
  slack:
    secure: aVCX6aZuIS4QWS2GPaAvMulnUm3L5IBtIQCRI+BMQSZcvKKwidKz/jjCaVUSK1kyjQRIBh61B/SykMTZKtxi7HV7CMklpCXJGZeJdwhDRK1ZnfjvkO0AayMYYJ0NwzHLvHaOGCxyZIvQqUT8S6HwUVpxg4wjjMzLefqCx2c/8Ek=
